### ISSUE TITLE
ISSUE: Uninstalled keymaster but still getting an "integration not found" error in logs

### ISSUE THREAD

**Issue by mifbody** [FutureTense/keymaster#162]
**Describe the bug**
I decided to no longer utilize Keymaster so I removed it from HACS, made sure there were no files in my config directory, and no entries in my config yaml file. But I'm still getting an error message that keymaster integration not found.

**Environment (please complete the following information):**

- Home Assistant OS 5.13
- core-2021.5.1
- supervisor-2021.04.3

**Logs**
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 10:16:25 AM (1 occurrences)
Last logged: 10:16:25 AM

Setup failed for keymaster: Integration not found.

**Comment by raman325** [comment]
The issue is that you uninstalled the integration from HACS before you removed the integration from your config. Now you still have keymaster in your config and when HA tries to load it, it fails because keymaster the integration isn't installed.

The steps to resolve this are:
1. Reinstall keymaster
2. Go into configuration > integrations, find the keymaster card, and click remove/delete from the ... menu
3. Uninstall keymaster

This isn't specific to keymaster, this is how all integrations work. And when you do step 2 (normally step 1 but you have to reinstall keymaster first in your case), it will clean everything up for you, including files written to disk, except for any lovelace dashboards you have added to your UI because we can't auto clean those up
