### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by DVarao** [FutureTense/keymaster#196]
Just a note for future update with auto lock:

if door has an open/close sensor enabled, and door is open, restart the auto lock timer.   If door is closed, then lock.  

Love your work!   Thanks!

**Comment by catchdave** [comment]
An alternative method that may suit environments that have door sensors is to start the timer countdown on door closed. So instead of "auto lock 2 mins after door opened", it becomes "auto lock 2 mins after door closed". Makes more sense since humans often leave doors open...

This can be achieved easily (and is my workaround for now) by using the built in automation event of "door closed for 2 mins"
