### ISSUE TITLE
Failed to add child locks to parent

### ISSUE THREAD

**Issue by Epod** [FutureTense/keymaster#212]
Clean install v0.56

Parent locks seem to get added fine, however when adding any lock as a child, the following error is generated

This error originated from a custom integration.

Logger: custom_components.keymaster.services
Source: custom_components/keymaster/services.py:86
Integration: keymaster (documentation, issues)
First occurred: 2:34:47 AM (1 occurrences)
Last logged: 2:34:47 AM

Error calling script.garageexterior_copy_from_parent_1 service call: Unable to find service script.garageexterior_copy_from_parent_1

**Comment by Xelinor** [comment]
So, I hit this problem too, and I was able to figure out the problem is in how you name your lock...or at least it was for me. If you have a space (i.e. 'Front Door') as the parent lock, when it goes to create the children it can't generate the name. My guess is you have it named 'garage exterior'?

Anyway, when I changed mine to be 'front_door_lock' it worked like a charm.

**Comment by grosejon** [comment]
I am having this same issue but I don't have any spaces in my naming.

> The automation "keymaster_override_parent_frontdoor_1_state_change" (automation.keymaster_override_parent_frontdoor_1_state_change) has an action that calls an unknown service: script.keymaster_frontdoor_copy_from_parent_1.

>This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

>To fix this error, [edit the automation](https://HOST/config/automation/edit/keymaster_override_parent_frontdoor_1_state_change) and remove the action that calls this service.

>Click on SUBMIT below to confirm you have fixed this automation.
