### ISSUE TITLE
Where to install the notification example script? 

### ISSUE THREAD

**Issue by pratul2002** [FutureTense/keymaster#214]
Hello: I have been using this app for some time now and for the life of me can't seem to be able to figure out where to seup the notification example script. Can you please help? Thank you!

**Comment by pratul2002** [comment]
OK.. so I added the code (after modifying it) to 
config/packages/keymaster/front_door/front_door_keymaster_common.yaml as follows:

script:
  front_door_manual_notify:
    mode: parallel
    sequence:
      - service: notify.mobile_app_iphone
        data:
          title: "{{ title }}"
          message: "{{ message }}"


but now I'm getting the following error:

Logger: homeassistant.components.automation.front_door_lock_notifications
Source: helpers/script.py:1324
Integration: Automation (documentation, issues)
First occurred: 6:13:33 PM (2 occurrences)
Last logged: 6:13:45 PM

front_door Lock Notifications: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'

Help?

**Comment by firstof9** [comment]
It doesn't go in that file.

**Comment by pratul2002** [comment]
Where should it go? I searched everywhere but couldn't find the details. Thanks for your help.
Also, the error above was because I was testing the automation from the UI. It worked as intended when I triggered it by operating the lock itself.

**Comment by firstof9** [comment]
The notification example goes where your other scripts are, usually `scripts.yaml`

**Comment by tykeal** [comment]
Copying from my answer in the [forum](https://community.home-assistant.io/t/keymaster-z-wave-lock-manager-and-scheduler/166419/1895?u=tykeal). It would be sort of nice if this was added to the wiki page on it so that it's easier for folks to do this!

--%<--
Use this button: [![Open your Home Assistant instance and show your scripts.](https://my.home-assistant.io/badges/scripts.svg)](https://my.home-assistant.io/redirect/scripts/) to get to your scripts area and then:

Select **Add Script**

Set the name to be keymaster_\<lockname\>_manual_notify (replace \<lockname\> with the name of your keymaster lock definition (spaces are converted to '\_')
Set the mode to Parallel

Add your notification configuration in the sequence. You must have at least _one_ action defined to be able to save the script.

**Comment by firstof9** [comment]
Would be neat if someone made a blueprint.

**Comment by tykeal** [comment]
Hmm.... maybe I can do that. Actually.... no I don't know if that's possible. Docs on blueprints are all about **Automations** and not **Scripts**

**Comment by firstof9** [comment]
Good point, we might need to depreciate the notification script and utilize the keymaster events for a blueprint instead

**Comment by raman325** [comment]
I didn't go into the level that you did but I updated the wiki page here: https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script

We can look into better tooling around the notifications
